// ─────────────────────────────────────────────────────────────────────────────
// Seed — demo media assets
// Blueprint 05: every asset carries an ownership label and a moderation state.
// Blueprint 07: an image without alt text is not accessible, so every row here
// has one.
//
// The seed writes real bytes. A `MediaAsset` row whose file is missing would
// render as a broken image in the demo, so each row below is backed by an SVG or
// text file generated on the spot and written through the configured storage
// root. Only formats we can synthesize are seeded — no fabricated audio or video
// assets, because shipping binaries in a seed is worse than not having them.
// ─────────────────────────────────────────────────────────────────────────────

import crypto from 'node:crypto';
import fs from 'node:fs/promises';
import path from 'node:path';

import { ContentOwnership, MediaKind, ModerationDecision } from '@prisma/client';

import { env } from '../../src/config/env';
import { prisma } from '../../src/core/prisma';
import { log, step } from './helpers';
import type { SchoolFixture } from './school.seed';

export interface MediaFixture {
  /** Banner image per subject key, used as lesson hero and activity thumbnail. */
  subjectBannerIds: Record<string, string>;
  /** Public school logo, servable without authentication. */
  logoId: string;
  /** A downloadable document, for the parent-letter link on the reports page. */
  parentLetterId: string;
}

const BANNERS = [
  { subjectKey: 'mathematics', label: 'Mathematics', color: '#4F46E5', accent: '#C7D2FE' },
  { subjectKey: 'english', label: 'English', color: '#0EA5E9', accent: '#BAE6FD' },
  { subjectKey: 'science', label: 'Science', color: '#16A34A', accent: '#BBF7D0' },
];

/** Flat banner: a coloured field, a title, and no external references. */
function bannerSvg(label: string, color: string, accent: string): string {
  return [
    '<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="600" viewBox="0 0 1200 600" role="img">',
    `<rect width="1200" height="600" fill="${color}"/>`,
    `<circle cx="1010" cy="120" r="220" fill="${accent}" fill-opacity="0.28"/>`,
    `<circle cx="180" cy="520" r="160" fill="${accent}" fill-opacity="0.22"/>`,
    `<text x="80" y="300" font-family="Georgia, serif" font-size="82" fill="#FFFFFF">${label}</text>`,
    '<text x="80" y="368" font-family="Helvetica, Arial, sans-serif" font-size="34"',
    ' fill="#FFFFFF" fill-opacity="0.86">Riverbank Primary</text>',
    '</svg>',
  ].join('');
}

function logoSvg(): string {
  return [
    '<svg xmlns="http://www.w3.org/2000/svg" width="240" height="240" viewBox="0 0 240 240" role="img">',
    '<rect width="240" height="240" rx="48" fill="#0F172A"/>',
    '<path d="M60 168V72l60 54 60-54v96" fill="none" stroke="#F5C451" stroke-width="18"',
    ' stroke-linecap="round" stroke-linejoin="round"/>',
    '</svg>',
  ].join('');
}

function parentLetter(): string {
  return [
    'Riverbank Primary — Midas Learning Cloud',
    '',
    'Dear parent or guardian,',
    '',
    'Your child now has a Midas account. They sign in with their student code and',
    'a four-digit PIN, both of which their class teacher will give them.',
    '',
    'You can ask the school for a copy of the data we hold about your child, or',
    'ask for it to be corrected or deleted, at any time.',
    '',
    'This is demo content created by the seed script.',
    '',
  ].join('\n');
}
interface AssetSpec {
  /** Stable key, so re-seeding overwrites the same file instead of adding one. */
  storageKey: string;
  fileName: string;
  kind: MediaKind;
  mimeType: string;
  body: string;
  altText: string | null;
  caption: string | null;
  width?: number;
  height?: number;
  isPublic?: boolean;
}

/**
 * Writes the bytes under the configured storage root, then upserts the row.
 * `storageKey` is unique in the schema, which is what makes this idempotent.
 */
async function ensureAsset(
  spec: AssetSpec,
  context: { schoolId: string; uploadedById: string; moderatedById: string; now: Date },
): Promise<string> {
  const content = Buffer.from(spec.body, 'utf8');
  const absolutePath = path.resolve(env.storage.localDir, spec.storageKey);
  await fs.mkdir(path.dirname(absolutePath), { recursive: true });
  await fs.writeFile(absolutePath, content);

  const columns = {
    kind: spec.kind,
    fileName: spec.fileName,
    originalFileName: spec.fileName,
    mimeType: spec.mimeType,
    byteSize: content.byteLength,
    checksumSha256: crypto.createHash('sha256').update(content).digest('hex'),
    width: spec.width ?? null,
    height: spec.height ?? null,
    altText: spec.altText,
    caption: spec.caption,
    ownership: ContentOwnership.MIDAS_ORIGINAL,
    licenseNote: 'Demo asset generated by the seed. Free to replace or delete.',
    moderationDecision: ModerationDecision.APPROVED,
    moderatedAt: context.now,
    moderatedById: context.moderatedById,
    isPublic: spec.isPublic ?? false,
    deletedAt: null,
  };

  const asset = await prisma.mediaAsset.upsert({
    where: { storageKey: spec.storageKey },
    update: columns,
    create: {
      ...columns,
      storageKey: spec.storageKey,
      schoolId: context.schoolId,
      uploadedById: context.uploadedById,
    },
    select: { id: true },
  });
  return asset.id;
}
export async function seedDemoMedia(
  fixture: SchoolFixture,
  people: { adminId: string; curriculumManagerId: string },
  now: Date,
): Promise<MediaFixture> {
  step('Demo media (blueprint 05, 07)');
  const context = {
    schoolId: fixture.schoolId,
    uploadedById: people.curriculumManagerId,
    moderatedById: people.adminId,
    now,
  };

  const subjectBannerIds: Record<string, string> = {};
  for (const banner of BANNERS) {
    subjectBannerIds[banner.subjectKey] = await ensureAsset(
      {
        storageKey: `demo/banners/${banner.subjectKey}.svg`,
        fileName: `${banner.subjectKey}-banner.svg`,
        kind: MediaKind.IMAGE,
        mimeType: 'image/svg+xml',
        body: bannerSvg(banner.label, banner.color, banner.accent),
        altText: `${banner.label} banner in the school colours.`,
        caption: `${banner.label} at Riverbank Primary`,
        width: 1200,
        height: 600,
      },
      context,
    );
  }

  const logoId = await ensureAsset(
    {
      storageKey: 'demo/brand/riverbank-logo.svg',
      fileName: 'riverbank-logo.svg',
      kind: MediaKind.IMAGE,
      mimeType: 'image/svg+xml',
      body: logoSvg(),
      altText: 'Riverbank Primary logo: a gold letter M on a dark square.',
      caption: null,
      width: 240,
      height: 240,
      isPublic: true,
    },
    context,
  );

  const parentLetterId = await ensureAsset(
    {
      storageKey: 'demo/documents/parent-letter.txt',
      fileName: 'parent-letter.txt',
      kind: MediaKind.DOCUMENT,
      mimeType: 'text/plain',
      body: parentLetter(),
      altText: null,
      caption: 'Letter sent home when accounts were issued.',
    },
    context,
  );

  log(`${BANNERS.length + 2} assets written under ${env.storage.localDir}`);
  return { subjectBannerIds, logoId, parentLetterId };
}
