import type { Permission } from '@/auth';

/**
 * Role permission bundles, for the dev preview harness only.
 *
 * Mirrored from `backend/src/core/rbac/permissions.ts` so a preview persona sees
 * exactly the menu a real user of that role would. Nothing in the shipped app
 * reads these — real permissions always come from `GET /auth/me`. This file
 * exists so the UI can be reviewed before the API is available, and it is excluded
 * from production builds along with the rest of `src/dev/`.
 */

const SELF_SERVICE: Permission[] = [
  'self.profile.read',
  'self.profile.update',
  'notification.read',
  'notification.preference.write',
  'support.create',
  'support.read.own',
];

export const STUDENT_PERMISSIONS: Permission[] = [
  ...SELF_SERVICE,
  'self.learning.participate',
  'lesson.read',
  'activity.read',
  'curriculum.read',
  'assessment.read',
  'assessment.attempt.start',
  'assessment.attempt.read',
  'learningpath.read',
  'progress.read.own',
  'mastery.read',
  'assignment.read',
  'assignment.submit',
  'gamification.read',
  'points.read',
  'badge.read',
  'reward.read',
  'reward.redeem',
  'mission.read',
  'companion.read',
  'companion.interact',
  'leaderboard.read',
  'report.read.own',
  'media.read',
  'content.report.create',
];

export const TEACHER_PERMISSIONS: Permission[] = [
  ...SELF_SERVICE,
  'school.read',
  'school.settings.read',
  'grade.read',
  'class.read',
  'subject.read',
  'term.read',
  'user.read',
  'usergroup.read',
  'curriculum.read',
  'lesson.read',
  'activity.read',
  'media.read',
  'media.upload',
  'content.report.create',
  'content.report.review',
  'assessment.read',
  'assessment.attempt.read',
  'assessment.response.override',
  'learningpath.read',
  'learningpath.write',
  'learningpath.approve',
  'recommendation.read',
  'recommendation.decide',
  'progress.read.scoped',
  'mastery.read',
  'mastery.override',
  'teacherassessment.write',
  'note.read',
  'note.write',
  'note.escalate',
  'assignment.read',
  'assignment.write',
  'assignment.grade',
  'assignment.excuse',
  'gamification.read',
  'points.read',
  'points.award',
  'badge.read',
  'badge.award',
  'reward.read',
  'mission.read',
  'mission.write',
  'companion.read',
  'leaderboard.read',
  'notification.send',
  'report.read.scoped',
  'report.export',
  'theme.read',
];

export const SCHOOL_ADMIN_PERMISSIONS: Permission[] = [
  ...TEACHER_PERMISSIONS,
  'school.update',
  'school.settings.write',
  'subscription.read',
  'entitlement.read',
  'entitlement.write',
  'theme.write',
  'theme.publish',
  'user.create',
  'user.update',
  'user.suspend',
  'user.archive',
  'user.credentials.reset',
  'role.assign',
  'role.revoke',
  'invitation.read',
  'invitation.create',
  'invitation.revoke',
  'usergroup.write',
  'session.revoke',
  'grade.write',
  'class.write',
  'class.roster.write',
  'subject.write',
  'term.write',
  'curriculum.write',
  'lesson.write',
  'activity.write',
  'content.review',
  'content.publish',
  'content.archive',
  'assessment.write',
  'assessment.publish',
  'gamification.config',
  'badge.write',
  'reward.write',
  'companion.config',
  'leaderboard.config',
  'notification.broadcast',
  'progress.read.school',
  'report.read.school',
  'audit.read.school',
  'consent.read',
  'retention.read',
];
