import { forwardRef, type InputHTMLAttributes } from 'react';
import { cn } from '@/lib/cn';
import { controlBase, controlBorder, controlPadding } from './control-styles';
import { useFieldContext } from './field-context';

export type InputProps = Omit<InputHTMLAttributes<HTMLInputElement>, 'id'> & {
  /** Override the id generated by the enclosing `Field`. Rarely needed. */
  id?: string;
};

/**
 * A single-line text input. Picks up its id, `aria-describedby` and invalid
 * state from the enclosing `Field`, so the accessible wiring cannot drift from
 * the visible label.
 */
export const Input = forwardRef<HTMLInputElement, InputProps>(function Input(
  { className, id, type = 'text', ...rest },
  ref,
) {
  const field = useFieldContext();

  return (
    <input
      ref={ref}
      id={id ?? field.inputId}
      type={type}
      aria-describedby={rest['aria-describedby'] ?? field.describedBy}
      aria-invalid={rest['aria-invalid'] ?? (field.isInvalid || undefined)}
      required={rest.required ?? field.isRequired}
      className={cn(controlBase, controlPadding, controlBorder(field.isInvalid), className)}
      {...rest}
    />
  );
});
